export const TODO_LIST_CREATE_ITEM = 'TODO_LIST_CREATE_ITEM';
export const TODO_LIST_DELETE_ITEM = 'TODO_LIST_DELETE_ITEM';
export const TODO_LIST_COMPLETE_ITEM = 'TODO_LIST_DELETE_ITEM';
export const TODO_LIST_EDIT_ITEM = 'TODO_LIST_EDIT_ITEM';
export const TODO_LIST_SAVE_ITEM = 'TODO_LIST_SAVE_ITEM';
