export const TODO_LIST_CREATE_ITEM = 'TODO_LIST_CREATE_ITEM';
export const TODO_LIST_DELETE_ITEM = 'TODO_LIST_DELETE_ITEM';
export const TODO_LIST_COMPLETE_ITEM = 'TODO_LIST_COMPLETE_ITEM';
export const TODO_LIST_EDIT_ITEM = 'TODO_LIST_EDIT_ITEM';
export const TODO_LIST_UPDATE_ITEM = 'TODO_LIST_UPDATE_ITEM';
export const TODO_LIST_CHANGE_FIELD = 'TODO_LIST_CHANGE_FIELD';
